LIST_PLAYERS_HEADERS = ["Player name", "Results"]

GAIN_REPUTATION_QUESTION = 5
GAIN_REPUTATION_ANSWER = 10
LOSE_REPUTATION = -2
GAIN_REPUTATION_ACCEPTED = 15
LOSE_REPUTATION_ACCEPTED = -15

PASSWORD_LENGTH_MIN = 3
PASSWORD_LENGTH_MAX = 21
PASSWORD_LENGTH = range(PASSWORD_LENGTH_MIN, PASSWORD_LENGTH_MAX + 1)

USERNAME_LENGTH_MIN = 4
USERNAME_LENGTH_MAX = 50
USERNAME_LENGTH = range(USERNAME_LENGTH_MIN, USERNAME_LENGTH_MAX + 1)